name: Testing api
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_KEY: ${{secrets.SERVICE_ACCOUNT_KEY}}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Create and activate virtual environment
        run: |
          python -m venv env
          source env/bin/activate
      - name: Installing dependencies
        run: |
          pip install dvc[gs]
          pip install -r requirements_test.txt
      - name: Test api
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl -r model-tracker
          pytest tests.py

